name: PickleLisp CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt install libedit-dev
      - name: Build
        run: |
          make
      - name: Run tests
        run: |
          ./test
