name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt install libedit-dev
          git clone https://github.com/orangeduck/mpc.git
      - name: Build
        run: |
          cd src/
          make
          cd ../test
          make
      - name: Run tests
        run: ./test/test
